spring:
  mvc:
    servlet:
      load-on-startup: 1
  thymeleaf:
    mode: HTML
  profiles:
    active: dev  # 指定开发环境或者生产环境
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png

