spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 日志
logging:
  level:
    root: info  # 级别 默认info 也可以设置warn等
    com.bear: debug
  file: log/blog-dev.log  # 文件位置  默认10M 自动切分



